#!/usr/bin/env python3
"""
Generate CI/CD pipeline files from images.yaml.

The target CI platform is controlled by .cascadeguard.yaml (in the repo
root, alongside images.yaml) or by the --platform flag:

  .cascadeguard.yaml:
    ci:
      platform: github   # default; also accepts: gitlab (future)

Supported platforms
-------------------
github (default)
    Emits four GitHub Actions workflow files under .github/workflows/:
      ci.yaml               — PR checks + push-to-main build/scan/sign pipeline
      build-image.yaml      — reusable workflow_call
      scheduled-scan.yaml   — nightly CVE re-scan of published images
      release.yaml          — tag-triggered sign+push+release-notes

gitlab (planned)
    Will emit .gitlab-ci.yml; not yet implemented.

Usage (inside the CascadeGuard Docker image):
  generate-ci --images-yaml /workspace/images.yaml --output-dir /workspace
  generate-ci --platform github   # explicit override
"""

import argparse
import sys
from pathlib import Path

import yaml

SUPPORTED_PLATFORMS = ("github",)
PLANNED_PLATFORMS = ("gitlab",)


# ---------------------------------------------------------------------------
# Config loading
# ---------------------------------------------------------------------------


def load_config(output_dir: Path) -> dict:
    """Load .cascadeguard.yaml from the repo root, returning {} if absent."""
    config_path = output_dir / ".cascadeguard.yaml"
    if config_path.exists():
        with open(config_path) as f:
            return yaml.safe_load(f) or {}
    return {}


def resolve_platform(config: dict, platform_flag: str | None) -> str:
    """
    Determine the target CI platform.

    Priority: --platform flag > cascadeguard.yaml ci.platform > default (github).
    """
    if platform_flag:
        return platform_flag.lower()
    return (config.get("ci") or {}).get("platform", "github").lower()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def load_images(images_yaml_path: Path) -> list:
    if not images_yaml_path.exists():
        print(f"ERROR: images.yaml not found at {images_yaml_path}", file=sys.stderr)
        sys.exit(1)
    with open(images_yaml_path) as f:
        return yaml.safe_load(f) or []


def write_workflow(path: Path, content: str, dry_run: bool = False) -> None:
    if dry_run:
        print(f"[dry-run] Would write {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"  wrote {path}")


# ---------------------------------------------------------------------------
# Workflow generators
# ---------------------------------------------------------------------------


def build_image_workflow(images: list) -> str:
    """Reusable workflow_call: build, scan, sign, push a single image."""
    return """\
# Auto-generated by CascadeGuard — do not edit by hand.
# Re-generate with: cascadeguard generate-ci
# https://github.com/cascadeguard/cascadeguard
name: build-image

'on':
  workflow_call:
    inputs:
      name:
        description: "Image name (from images.yaml)"
        required: true
        type: string
      context:
        description: "Docker build context path relative to repo root"
        required: false
        type: string
        default: "."
      dockerfile:
        description: "Path to Dockerfile relative to repo root"
        required: true
        type: string
      registry:
        description: "Target container registry"
        required: true
        type: string
      image:
        description: "Image repository name (e.g. python)"
        required: true
        type: string
      tag:
        description: "Image tag (e.g. 3.12-slim)"
        required: true
        type: string
      push:
        description: "Push image to registry after build"
        required: false
        type: boolean
        default: false
      sign:
        description: "Sign image with Cosign after push"
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  packages: write
  id-token: write  # required for keyless Cosign signing

jobs:
  build:
    name: Build ${{ inputs.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: inputs.push
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build${{ inputs.push && ' and push' || '' }} image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: ${{ inputs.push }}
          load: ${{ !inputs.push }}  # load into local daemon on PRs so scanners can find the image
          tags: ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.tag }}
          cache-from: type=gha,scope=${{ inputs.name }}
          # cache-to requires push=true; load=true is incompatible with GHA cache export
          cache-to: ${{ inputs.push && format('type=gha,scope={0},mode=max', inputs.name) || '' }}

      - name: Scan with Grype
        uses: anchore/scan-action@v6
        with:
          # On PRs (load=true), use the local image ID to avoid registry pull attempts
          image: ${{ inputs.push && format('{0}/{1}:{2}', inputs.registry, inputs.image, inputs.tag) || steps.build.outputs.imageid }}
          fail-build: true
          severity-cutoff: critical
          output-format: table

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          # On PRs (load=true), use the local image ID to avoid registry pull attempts
          image-ref: ${{ inputs.push && format('{0}/{1}:{2}', inputs.registry, inputs.image, inputs.tag) || steps.build.outputs.imageid }}
          format: table
          exit-code: "1"
          ignore-unfixed: true
          severity: CRITICAL

      - name: Generate SBOM (Syft)
        if: inputs.push
        uses: anchore/sbom-action@v0
        with:
          image: ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.tag }}
          format: spdx-json
          output-file: sbom-${{ inputs.name }}.spdx.json

      - name: Sign image with Cosign
        if: inputs.push && inputs.sign
        uses: sigstore/cosign-installer@v3
      - name: Run Cosign keyless sign
        if: inputs.push && inputs.sign
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign --yes \\
            ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.tag }}@${{ steps.build.outputs.digest }}
"""


def ci_workflow(images: list) -> str:
    """PR + push-to-main pipeline: build all images in a matrix."""
    matrix_items = []
    for img in images:
        context = img.get("context", ".")
        matrix_items.append(
            f"            - name: {img['name']}\n"
            f"              context: {context}\n"
            f"              dockerfile: {img['dockerfile']}\n"
            f"              registry: {img['registry']}\n"
            f"              image: {img['image']}\n"
            f"              tag: \"{img['tag']}\""
        )
    matrix_block = "\n".join(matrix_items)

    return f"""\
# Auto-generated by CascadeGuard — do not edit by hand.
# Re-generate with: cascadeguard generate-ci
# https://github.com/cascadeguard/cascadeguard
name: CI

'on':
  push:
    branches: [main]
    paths:
      - "images/**"
      - "images.yaml"
      - "shared/**"
      - ".github/workflows/**"
  pull_request:
    branches: [main]
    paths:
      - "images/**"
      - "images.yaml"
      - "shared/**"
      - ".github/workflows/**"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    name: Build ${{{{ matrix.name }}}}
    strategy:
      fail-fast: false
      matrix:
        include:
{matrix_block}
    uses: ./.github/workflows/build-image.yaml
    with:
      name: ${{{{ matrix.name }}}}
      context: ${{{{ matrix.context }}}}
      dockerfile: ${{{{ matrix.dockerfile }}}}
      registry: ${{{{ matrix.registry }}}}
      image: ${{{{ matrix.image }}}}
      tag: ${{{{ matrix.tag }}}}
      # Push only on main branch, not on PRs
      push: ${{{{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}}}
      sign: ${{{{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}}}
    secrets: inherit
"""


def scheduled_scan_workflow(images: list) -> str:
    """Nightly CVE re-scan of all published images."""
    matrix_items = []
    for img in images:
        matrix_items.append(
            f"            - name: {img['name']}\n"
            f"              registry: {img['registry']}\n"
            f"              image: {img['image']}\n"
            f"              tag: \"{img['tag']}\""
        )
    matrix_block = "\n".join(matrix_items)

    return f"""\
# Auto-generated by CascadeGuard — do not edit by hand.
# Re-generate with: cascadeguard generate-ci
# https://github.com/cascadeguard/cascadeguard
name: Scheduled CVE Scan

'on':
  schedule:
    # 02:00 UTC every day
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: read
  issues: write  # open CVE issues automatically
  security-events: write

jobs:
  scan:
    name: Scan ${{{{ matrix.name }}}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
{matrix_block}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull published image
        run: docker pull ${{{{ matrix.registry }}}}/${{{{ matrix.image }}}}:${{{{ matrix.tag }}}}

      - name: Scan with Grype
        id: grype
        uses: anchore/scan-action@v6
        with:
          image: ${{{{ matrix.registry }}}}/${{{{ matrix.image }}}}:${{{{ matrix.tag }}}}
          fail-build: false
          severity-cutoff: high
          output-format: json
          output-file: grype-${{{{ matrix.name }}}}.json

      - name: Scan with Trivy (SARIF)
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: ${{{{ matrix.registry }}}}/${{{{ matrix.image }}}}:${{{{ matrix.tag }}}}
          format: sarif
          output: trivy-${{{{ matrix.name }}}}.sarif
          severity: CRITICAL
          ignore-unfixed: true

      - name: Upload Trivy SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-${{{{ matrix.name }}}}.sarif
          category: trivy-${{{{ matrix.name }}}}

      - name: Open CVE issue on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const title = `[CVE] New vulnerabilities in ${{{{ matrix.name }}}}`;
            const body = [
              `## Automated CVE Alert`,
              ``,
              `The nightly scan detected new unpatched vulnerabilities in \\`${{{{ matrix.registry }}}}/${{{{ matrix.image }}}}:${{{{ matrix.tag }}}}\\`.`,
              ``,
              `**Scan date:** ${{{{ github.run_started_at }}}}`,
              `**Run:** ${{{{ github.server_url }}}}/${{{{ github.repository }}}}/actions/runs/${{{{ github.run_id }}}}`,
              ``,
              `Review the SARIF results in the Security tab and patch per [CVE-STRATEGY.md](./CVE-STRATEGY.md).`,
            ].join('\\n');
            await github.rest.issues.create({{
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              labels: ['vulnerability', 'automated'],
            }});
"""


def release_workflow(images: list) -> str:
    """Tag-triggered sign, push, and release-notes workflow."""
    matrix_items = []
    for img in images:
        context = img.get("context", ".")
        matrix_items.append(
            f"            - name: {img['name']}\n"
            f"              context: {context}\n"
            f"              dockerfile: {img['dockerfile']}\n"
            f"              registry: {img['registry']}\n"
            f"              image: {img['image']}\n"
            f"              tag: \"{img['tag']}\""
        )
    matrix_block = "\n".join(matrix_items)

    return f"""\
# Auto-generated by CascadeGuard — do not edit by hand.
# Re-generate with: cascadeguard generate-ci
# https://github.com/cascadeguard/cascadeguard
name: Release

'on':
  push:
    tags:
      - "v*"

permissions:
  contents: write  # create GitHub Release
  packages: write
  id-token: write  # Cosign keyless signing

jobs:
  release-images:
    name: Release ${{{{ matrix.name }}}}
    strategy:
      fail-fast: false
      matrix:
        include:
{matrix_block}
    uses: ./.github/workflows/build-image.yaml
    with:
      name: ${{{{ matrix.name }}}}
      context: ${{{{ matrix.context }}}}
      dockerfile: ${{{{ matrix.dockerfile }}}}
      registry: ${{{{ matrix.registry }}}}
      image: ${{{{ matrix.image }}}}
      tag: ${{{{ matrix.tag }}}}
      push: true
      sign: true
    secrets: inherit

  create-release:
    name: Create GitHub Release
    needs: release-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history for changelog

      - name: Generate changelog
        id: changelog
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -n "$PREV_TAG" ]; then
            CHANGES=$(git log --pretty=format:"- %s (%h)" "$PREV_TAG"..HEAD)
          else
            CHANGES=$(git log --pretty=format:"- %s (%h)")
          fi
          echo "CHANGES<<EOF" >> "$GITHUB_OUTPUT"
          echo "$CHANGES" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Build image list for release notes
        id: image-list
        run: |
          IMAGES=$(cat images.yaml | grep -E '^- name:|  image:|  tag:' | paste - - - | \\
            sed 's/- name: //;s/  image: //;s/  tag: //' | \\
            awk '{{print "| `"$1"` | `ghcr.io/cascadeguard/"$2":"$3"` |"}}')
          echo "IMAGES<<EOF" >> "$GITHUB_OUTPUT"
          echo "$IMAGES" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: actions/github-script@v7
        env:
          CHANGES: ${{{{ steps.changelog.outputs.CHANGES }}}}
          IMAGES: ${{{{ steps.image-list.outputs.IMAGES }}}}
        with:
          script: |
            const tag = context.ref.replace('refs/tags/', '');
            const body = [
              `## Images`,
              ``,
              `| Name | Pull |`,
              `|------|------|`,
              process.env.IMAGES,
              ``,
              `## What's Changed`,
              ``,
              process.env.CHANGES,
              ``,
              `---`,
              `All images are signed with [Cosign](https://docs.sigstore.dev/cosign/overview/) keyless signing via Sigstore.`,
            ].join('\\n');
            await github.rest.repos.createRelease({{
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
              name: tag,
              body,
              draft: false,
              prerelease: tag.includes('-'),
            }});
"""


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def generate_github_actions(images: list, output_dir: Path, dry_run: bool) -> None:
    """Emit the four GitHub Actions workflow files."""
    workflows_dir = output_dir / ".github" / "workflows"
    print(f"  platform : github")
    print(f"  output   : {workflows_dir}")

    write_workflow(workflows_dir / "build-image.yaml", build_image_workflow(images), dry_run)
    write_workflow(workflows_dir / "ci.yaml", ci_workflow(images), dry_run)
    write_workflow(workflows_dir / "scheduled-scan.yaml", scheduled_scan_workflow(images), dry_run)
    write_workflow(workflows_dir / "release.yaml", release_workflow(images), dry_run)


def generate_ci(
    images_yaml_path: Path,
    output_dir: Path,
    dry_run: bool = False,
    platform: str | None = None,
) -> None:
    images = load_images(images_yaml_path)
    if not images:
        print("WARNING: images.yaml is empty — no workflows generated.", file=sys.stderr)
        return

    config = load_config(output_dir)
    resolved_platform = resolve_platform(config, platform)

    print(f"Generating CI resources for {len(images)} image(s)…")

    if resolved_platform == "github":
        generate_github_actions(images, output_dir, dry_run)
    elif resolved_platform in PLANNED_PLATFORMS:
        print(
            f"ERROR: platform '{resolved_platform}' is planned but not yet implemented.\n"
            f"       Supported platforms: {', '.join(SUPPORTED_PLATFORMS)}",
            file=sys.stderr,
        )
        sys.exit(1)
    else:
        print(
            f"ERROR: unknown platform '{resolved_platform}'.\n"
            f"       Supported platforms: {', '.join(SUPPORTED_PLATFORMS)}",
            file=sys.stderr,
        )
        sys.exit(1)

    print("Done.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Generate CI/CD pipeline files from images.yaml. "
            "Platform defaults to 'github'; override via cascadeguard.yaml or --platform."
        )
    )
    parser.add_argument(
        "--images-yaml",
        default="/workspace/images.yaml",
        help="Path to images.yaml (default: /workspace/images.yaml)",
    )
    parser.add_argument(
        "--output-dir",
        default="/workspace",
        help="Repo root — .cascadeguard.yaml is read from here; output written relative to here (default: /workspace)",
    )
    parser.add_argument(
        "--platform",
        default=None,
        help=f"CI platform to target ({', '.join(SUPPORTED_PLATFORMS)}). "
             f"Overrides .cascadeguard.yaml ci.platform. Default: github.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be written without creating files",
    )
    args = parser.parse_args()

    generate_ci(
        images_yaml_path=Path(args.images_yaml),
        output_dir=Path(args.output_dir),
        dry_run=args.dry_run,
        platform=args.platform,
    )


if __name__ == "__main__":
    main()
