"""Pluggable storage backends for ImageFactoryTool.

YamlBackend  – existing GitOps behaviour (read/write YAML state files).
DatabaseBackend – SaaS mode (read/write via SQLAlchemy to PostgreSQL).
"""

from __future__ import annotations

import uuid
import yaml
from abc import ABC, abstractmethod
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

import logging

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Abstract base
# ---------------------------------------------------------------------------

class StorageBackend(ABC):
    """Interface that ImageFactoryTool uses for all persistence."""

    @abstractmethod
    def load_images(self) -> List[Dict]:
        """Return the list of enrolled image configs (equivalent to images.yaml)."""

    @abstractmethod
    def load_image_state(self, name: str) -> Optional[Dict]:
        """Load existing state for a managed/external image, or None."""

    @abstractmethod
    def save_image_state(self, state: Dict) -> None:
        """Persist image state (upsert)."""

    @abstractmethod
    def load_base_image_state(self, name: str) -> Optional[Dict]:
        """Load existing state for a base image, or None."""

    @abstractmethod
    def save_base_image_state(self, state: Dict) -> None:
        """Persist base-image state (upsert)."""

    @abstractmethod
    def save_dependency(self, image_name: str, base_image_name: str) -> None:
        """Record that *image_name* depends on *base_image_name*."""


# ---------------------------------------------------------------------------
# YAML backend – preserves original OSS/GitOps behaviour
# ---------------------------------------------------------------------------

class YamlBackend(StorageBackend):
    """Read/write state as YAML files on disk (GitOps mode)."""

    def __init__(self, root_dir: Path):
        self.root_dir = root_dir
        self.images_yaml_path = root_dir / "images.yaml"
        self.state_images_dir = root_dir / "state" / "images"
        self.state_base_images_dir = root_dir / "state" / "base-images"

        self.state_images_dir.mkdir(parents=True, exist_ok=True)
        self.state_base_images_dir.mkdir(parents=True, exist_ok=True)

    # -- helpers for formatted YAML output (moved from ImageFactoryTool) ----

    @staticmethod
    def _yaml_value(value):
        if value is None:
            return "null"
        elif isinstance(value, bool):
            return str(value).lower()
        elif isinstance(value, str):
            return value
        else:
            return str(value)

    # -- StorageBackend implementation --------------------------------------

    def load_images(self) -> List[Dict]:
        if not self.images_yaml_path.exists():
            logger.warning(f"images.yaml not found at {self.images_yaml_path}")
            return []
        with open(self.images_yaml_path, "r") as f:
            data = yaml.safe_load(f) or []
        logger.info(f"Loaded {len(data)} images from images.yaml")
        return data

    def load_image_state(self, name: str) -> Optional[Dict]:
        state_file = self.state_images_dir / f"{name}.yaml"
        if not state_file.exists():
            return None
        with open(state_file, "r") as f:
            return yaml.safe_load(f) or {}

    def save_image_state(self, state: Dict) -> None:
        name = state["name"]
        file_path = self.state_images_dir / f"{name}.yaml"
        self._write_image_state(state, file_path)

    def load_base_image_state(self, name: str) -> Optional[Dict]:
        state_file = self.state_base_images_dir / f"{name}.yaml"
        if not state_file.exists():
            return None
        with open(state_file, "r") as f:
            return yaml.safe_load(f) or {}

    def save_base_image_state(self, state: Dict) -> None:
        name = state["name"]
        file_path = self.state_base_images_dir / f"{name}.yaml"
        self._write_base_image_state(state, file_path)

    def save_dependency(self, image_name: str, base_image_name: str) -> None:
        # In YAML mode dependencies are embedded in the image state file
        # (baseImages list) — no separate action needed.
        pass

    # -- YAML writing (moved verbatim from ImageFactoryTool) ----------------

    def _write_image_state(self, state: Dict, file_path: Path):
        is_external = state.get("discoveryStatus") == "external"
        yv = self._yaml_value

        with open(file_path, "w") as f:
            f.write(f"# Auto-generated by Image Factory\n")
            f.write(f"# This file tracks the state of the {state['name']} image\n")
            f.write(f"name: {state['name']}\n")
            f.write(f"enrolledAt: {yaml.dump(state['enrolledAt'], default_flow_style=True).strip()}\n")
            f.write(f"lastDiscovery: {yaml.dump(state['lastDiscovery'], default_flow_style=True).strip()}\n")
            f.write(f"discoveryStatus: {state['discoveryStatus']}\n\n")

            f.write("# Enrollment configuration (copied from images.yaml for reference)\n")
            f.write("enrollment:\n")
            enrollment = state["enrollment"]
            f.write(f"  registry: {enrollment['registry']}\n")
            f.write(f"  repository: {enrollment['repository']}\n")
            if "source" in enrollment:
                f.write("  source:\n")
                for key, value in enrollment["source"].items():
                    f.write(f"    {key}: {value}\n")
            f.write(f"  rebuildDelay: {enrollment['rebuildDelay']}\n")
            f.write(f"  autoRebuild: {str(enrollment['autoRebuild']).lower()}\n\n")

            if is_external:
                f.write("# Warehouse configuration (for CDK8s)\n")
                if "allowTags" in state:
                    f.write(f"allowTags: {state['allowTags']}\n")
                if "imageSelectionStrategy" in state:
                    f.write(f"imageSelectionStrategy: {state['imageSelectionStrategy']}\n")
                if "repoURL" in state:
                    f.write(f"repoURL: {state['repoURL']}\n")
                f.write("\n")

            f.write("# Discovered from Dockerfile parsing\n")
            if not is_external:
                f.write("# References to base image state files (not inline data)\n")
            f.write("baseImages:")
            if state["baseImages"]:
                f.write("\n")
                for base in state["baseImages"]:
                    f.write(f"  - {base}\n")
            else:
                f.write(" []\n")
            f.write("\n")

            f.write("# Current published state (from registry/Kargo)\n")
            f.write(f"currentVersion: {yv(state.get('currentVersion'))}\n")
            f.write(f"currentDigest: {yv(state.get('currentDigest'))}\n")
            last_built = state.get("lastBuilt")
            if last_built:
                f.write(f"lastBuilt: {yaml.dump(last_built, default_flow_style=True).strip()}\n\n")
            else:
                f.write(f"lastBuilt: null\n")

    def _write_base_image_state(self, state: Dict, file_path: Path):
        yv = self._yaml_value

        with open(file_path, "w") as f:
            f.write(f"# Auto-generated by Image Factory\n")
            f.write(f"# This file tracks the upstream {state['fullImage']} base image\n\n")

            f.write("# Normalized identifier (used as filename and reference)\n")
            f.write(f"name: {state['name']}\n\n")

            f.write("# Original image reference\n")
            f.write(f"fullImage: {state['fullImage']}\n")
            f.write(f"registry: {state['registry']}\n")
            f.write(f"repository: {state['repository']}\n")
            f.write(f"tag: {state['tag']}\n\n")

            f.write("# Warehouse configuration (for CDK8s)\n")
            f.write(f"allowTags: {state['allowTags']}\n")
            f.write(f"imageSelectionStrategy: {state['imageSelectionStrategy']}\n")
            f.write(f"repoURL: {state['repoURL']}\n\n")

            f.write("# Discovery\n")
            f.write(f"firstDiscovered: {yaml.dump(state['firstDiscovered'], default_flow_style=True).strip()}\n")
            f.write(f"lastChecked: {yaml.dump(state['lastChecked'], default_flow_style=True).strip()}\n\n")

            f.write("# Current state\n")
            f.write(f"currentDigest: {yv(state['currentDigest'])}\n")
            f.write(f"lastUpdated: {yv(state['lastUpdated'])}  # Will be set when digest first changes\n")
            f.write(f"previousDigest: {yv(state['previousDigest'])}\n\n")

            f.write("# Rebuild eligibility\n")
            f.write("rebuildEligibleAt:\n")
            f.write(f"  default: {yv(state['rebuildEligibleAt']['default'])}  # Will be calculated as lastUpdated + rebuildDelay\n\n")

            f.write("# Metadata from registry\n")
            if state.get("metadata") and state["metadata"]:
                f.write("metadata:\n")
                for key, value in state["metadata"].items():
                    f.write(f"  {key}: {yaml.dump(value, default_flow_style=True).strip()}\n")
            else:
                f.write("metadata: {}\n")
            f.write("\n")

            f.write("# Update history (last 10 digest changes)\n")
            if state.get("updateHistory"):
                f.write("updateHistory:\n")
                for entry in state["updateHistory"]:
                    f.write(f"  - {yaml.dump(entry, default_flow_style=True).strip()}\n")
            else:
                f.write("updateHistory: []\n")

            if state.get("lastDiscovery") is not None:
                f.write(f"\nlastDiscovery: {yv(state['lastDiscovery'])}\n")


# ---------------------------------------------------------------------------
# Database backend – SaaS mode
# ---------------------------------------------------------------------------

class DatabaseBackend(StorageBackend):
    """Read/write state via SQLAlchemy session (SaaS multi-tenant mode).

    Requires a bound SQLAlchemy ``Session`` and an ``org_id`` (UUID) that
    scopes all queries to a single tenant.
    """

    def __init__(self, session, org_id: uuid.UUID):
        # Deferred import so the app/ package doesn't hard-depend on saas/
        from saas.db.models import (
            AnalysisJob,
            Image,
            ImageDependency,
            ImageState,
        )

        self._session = session
        self._org_id = org_id
        self._Image = Image
        self._ImageState = ImageState
        self._ImageDependency = ImageDependency
        self._AnalysisJob = AnalysisJob

    # -- helpers ------------------------------------------------------------

    def _get_image(self, name: str):
        return (
            self._session.query(self._Image)
            .filter_by(org_id=self._org_id, name=name)
            .first()
        )

    def _get_or_create_image(self, name: str, defaults: Dict):
        img = self._get_image(name)
        if img is None:
            img = self._Image(
                org_id=self._org_id,
                name=name,
                type=defaults.get("type", "managed"),
                registry=defaults.get("registry", "docker.io"),
                repository=defaults.get("repository", name),
                tag_pattern=defaults.get("tag_pattern"),
                source_provider=defaults.get("source_provider"),
                source_repo=defaults.get("source_repo"),
                source_branch=defaults.get("source_branch"),
                source_dockerfile=defaults.get("source_dockerfile"),
                auto_rebuild=defaults.get("auto_rebuild", True),
                rebuild_delay_days=defaults.get("rebuild_delay_days", 7),
            )
            self._session.add(img)
            self._session.flush()
        return img

    # -- StorageBackend implementation --------------------------------------

    def load_images(self) -> List[Dict]:
        """Load enrolled images from the database.

        Returns dicts shaped like images.yaml entries so that
        ImageFactoryTool.process() can consume them unchanged.
        """
        rows = (
            self._session.query(self._Image)
            .filter_by(org_id=self._org_id)
            .filter(self._Image.type.in_(["managed", "external"]))
            .all()
        )
        result = []
        for img in rows:
            entry: Dict = {
                "name": img.name,
                "registry": img.registry,
                "repository": img.repository,
            }
            if img.source_repo:
                entry["source"] = {
                    "provider": img.source_provider or "github",
                    "repo": img.source_repo,
                    "branch": img.source_branch or "main",
                }
                if img.source_dockerfile:
                    entry["source"]["dockerfile"] = img.source_dockerfile
            if img.tag_pattern:
                entry["allowTags"] = img.tag_pattern
            entry["autoRebuild"] = img.auto_rebuild
            entry["rebuildDelay"] = f"{img.rebuild_delay_days or 7}d"
            result.append(entry)
        logger.info(f"Loaded {len(result)} images from database (org {self._org_id})")
        return result

    def load_image_state(self, name: str) -> Optional[Dict]:
        img = self._get_image(name)
        if img is None or img.state is None:
            return None
        st = img.state
        return {
            "name": img.name,
            "currentDigest": st.current_digest,
            "currentVersion": st.current_version,
            "lastBuilt": st.last_built_at.isoformat() if st.last_built_at else None,
            "enrolledAt": img.created_at.isoformat() if img.created_at else None,
            "rebuildEligibleAt": st.rebuild_eligible_at.isoformat() if st.rebuild_eligible_at else None,
        }

    def save_image_state(self, state: Dict) -> None:
        name = state["name"]

        # Determine image type
        is_external = state.get("discoveryStatus") == "external"
        enrollment = state.get("enrollment", {})
        source = enrollment.get("source", {})

        defaults = {
            "type": "external" if is_external else "managed",
            "registry": enrollment.get("registry", "docker.io"),
            "repository": enrollment.get("repository", name),
            "source_provider": source.get("provider"),
            "source_repo": source.get("repo"),
            "source_branch": source.get("branch"),
            "source_dockerfile": source.get("dockerfile"),
            "auto_rebuild": enrollment.get("autoRebuild", True),
            "tag_pattern": state.get("allowTags"),
        }
        # Parse rebuildDelay like "7d" → 7
        rd = enrollment.get("rebuildDelay", "7d")
        if isinstance(rd, str) and rd.endswith("d"):
            try:
                defaults["rebuild_delay_days"] = int(rd[:-1])
            except ValueError:
                defaults["rebuild_delay_days"] = 7
        elif isinstance(rd, int):
            defaults["rebuild_delay_days"] = rd

        img = self._get_or_create_image(name, defaults)

        # Upsert ImageState
        now = datetime.now(timezone.utc)
        if img.state is None:
            img.state = self._ImageState(
                image_id=img.id,
                status=state.get("discoveryStatus", "pending"),
                current_digest=state.get("currentDigest"),
                current_version=state.get("currentVersion"),
                last_built_at=None,
                last_checked_at=now,
            )
        else:
            img.state.last_checked_at = now
            if state.get("currentDigest"):
                img.state.current_digest = state["currentDigest"]
            if state.get("currentVersion"):
                img.state.current_version = state["currentVersion"]

        self._session.flush()

    def load_base_image_state(self, name: str) -> Optional[Dict]:
        img = (
            self._session.query(self._Image)
            .filter_by(org_id=self._org_id, name=name, type="base")
            .first()
        )
        if img is None:
            return None
        st = img.state
        return {
            "name": img.name,
            "fullImage": f"{img.registry}/{img.repository}:{img.tag_pattern or 'latest'}",
            "registry": img.registry,
            "repository": img.repository,
            "tag": img.tag_pattern or "latest",
            "currentDigest": st.current_digest if st else None,
            "lastUpdated": st.last_checked_at.isoformat() if st and st.last_checked_at else None,
            "previousDigest": None,
            "firstDiscovered": img.created_at.isoformat() if img.created_at else None,
            "lastChecked": st.last_checked_at.isoformat() if st and st.last_checked_at else None,
            "rebuildEligibleAt": {"default": st.rebuild_eligible_at.isoformat() if st and st.rebuild_eligible_at else None},
            "metadata": {},
            "updateHistory": [],
        }

    def save_base_image_state(self, state: Dict) -> None:
        name = state["name"]
        defaults = {
            "type": "base",
            "registry": state.get("registry", "docker.io"),
            "repository": state.get("repository", name),
            "tag_pattern": state.get("tag"),
        }
        img = self._get_or_create_image(name, defaults)

        now = datetime.now(timezone.utc)
        if img.state is None:
            img.state = self._ImageState(
                image_id=img.id,
                status="tracking",
                current_digest=state.get("currentDigest"),
                last_checked_at=now,
            )
        else:
            img.state.last_checked_at = now
            if state.get("currentDigest"):
                img.state.current_digest = state["currentDigest"]

        self._session.flush()

    def save_dependency(self, image_name: str, base_image_name: str) -> None:
        img = self._get_image(image_name)
        base = self._get_image(base_image_name)
        if img is None or base is None:
            logger.warning(f"Cannot save dependency {image_name} -> {base_image_name}: image(s) not found")
            return

        existing = (
            self._session.query(self._ImageDependency)
            .filter_by(image_id=img.id, base_image_id=base.id)
            .first()
        )
        if existing is None:
            dep = self._ImageDependency(
                image_id=img.id,
                base_image_id=base.id,
            )
            self._session.add(dep)
            self._session.flush()
