"""Pluggable storage backends for ImageFactoryTool.

YamlBackend  – existing GitOps behaviour (read/write YAML state files).

The DatabaseBackend for SaaS mode lives in saas/storage.py (not part of the
open-source distribution).
"""

from __future__ import annotations

import yaml
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Dict, List, Optional

import logging

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Abstract base
# ---------------------------------------------------------------------------

class StorageBackend(ABC):
    """Interface that ImageFactoryTool uses for all persistence."""

    @abstractmethod
    def load_images(self) -> List[Dict]:
        """Return the list of enrolled image configs (equivalent to images.yaml)."""

    @abstractmethod
    def load_image_state(self, name: str) -> Optional[Dict]:
        """Load existing state for a managed/external image, or None."""

    @abstractmethod
    def save_image_state(self, state: Dict) -> None:
        """Persist image state (upsert)."""

    @abstractmethod
    def load_base_image_state(self, name: str) -> Optional[Dict]:
        """Load existing state for a base image, or None."""

    @abstractmethod
    def save_base_image_state(self, state: Dict) -> None:
        """Persist base-image state (upsert)."""

    @abstractmethod
    def save_dependency(self, image_name: str, base_image_name: str) -> None:
        """Record that *image_name* depends on *base_image_name*."""


# ---------------------------------------------------------------------------
# YAML backend – preserves original OSS/GitOps behaviour
# ---------------------------------------------------------------------------

class YamlBackend(StorageBackend):
    """Read/write state as YAML files on disk (GitOps mode)."""

    def __init__(self, root_dir: Path):
        self.root_dir = root_dir
        self.images_yaml_path = root_dir / "images.yaml"
        self.state_images_dir = root_dir / "state" / "images"
        self.state_base_images_dir = root_dir / "state" / "base-images"

        self.state_images_dir.mkdir(parents=True, exist_ok=True)
        self.state_base_images_dir.mkdir(parents=True, exist_ok=True)

    # -- helpers for formatted YAML output (moved from ImageFactoryTool) ----

    @staticmethod
    def _yaml_value(value):
        if value is None:
            return "null"
        elif isinstance(value, bool):
            return str(value).lower()
        elif isinstance(value, str):
            return value
        else:
            return str(value)

    # -- StorageBackend implementation --------------------------------------

    def load_images(self) -> List[Dict]:
        if not self.images_yaml_path.exists():
            logger.warning(f"images.yaml not found at {self.images_yaml_path}")
            return []
        with open(self.images_yaml_path, "r") as f:
            data = yaml.safe_load(f) or []
        logger.info(f"Loaded {len(data)} images from images.yaml")
        return data

    def load_image_state(self, name: str) -> Optional[Dict]:
        state_file = self.state_images_dir / f"{name}.yaml"
        if not state_file.exists():
            return None
        with open(state_file, "r") as f:
            return yaml.safe_load(f) or {}

    def save_image_state(self, state: Dict) -> None:
        name = state["name"]
        file_path = self.state_images_dir / f"{name}.yaml"
        self._write_image_state(state, file_path)

    def load_base_image_state(self, name: str) -> Optional[Dict]:
        state_file = self.state_base_images_dir / f"{name}.yaml"
        if not state_file.exists():
            return None
        with open(state_file, "r") as f:
            return yaml.safe_load(f) or {}

    def save_base_image_state(self, state: Dict) -> None:
        name = state["name"]
        file_path = self.state_base_images_dir / f"{name}.yaml"
        self._write_base_image_state(state, file_path)

    def save_dependency(self, image_name: str, base_image_name: str) -> None:
        # In YAML mode dependencies are embedded in the image state file
        # (baseImages list) — no separate action needed.
        pass

    # -- YAML writing (moved verbatim from ImageFactoryTool) ----------------

    def _write_image_state(self, state: Dict, file_path: Path):
        is_external = state.get("discoveryStatus") == "external"
        yv = self._yaml_value

        with open(file_path, "w") as f:
            f.write(f"# Auto-generated by Image Factory\n")
            f.write(f"# This file tracks the state of the {state['name']} image\n")
            f.write(f"name: {state['name']}\n")
            f.write(f"enrolledAt: {yaml.dump(state['enrolledAt'], default_flow_style=True).strip()}\n")
            f.write(f"lastDiscovery: {yaml.dump(state['lastDiscovery'], default_flow_style=True).strip()}\n")
            f.write(f"discoveryStatus: {state['discoveryStatus']}\n\n")

            f.write("# Enrollment configuration (copied from images.yaml for reference)\n")
            f.write("enrollment:\n")
            enrollment = state["enrollment"]
            f.write(f"  registry: {enrollment['registry']}\n")
            f.write(f"  repository: {enrollment['repository']}\n")
            if "source" in enrollment:
                f.write("  source:\n")
                for key, value in enrollment["source"].items():
                    f.write(f"    {key}: {value}\n")
            f.write(f"  rebuildDelay: {enrollment['rebuildDelay']}\n")
            f.write(f"  autoRebuild: {str(enrollment['autoRebuild']).lower()}\n\n")

            if is_external:
                f.write("# Warehouse configuration (for CDK8s)\n")
                if "allowTags" in state:
                    f.write(f"allowTags: {state['allowTags']}\n")
                if "imageSelectionStrategy" in state:
                    f.write(f"imageSelectionStrategy: {state['imageSelectionStrategy']}\n")
                if "repoURL" in state:
                    f.write(f"repoURL: {state['repoURL']}\n")
                f.write("\n")

            f.write("# Discovered from Dockerfile parsing\n")
            if not is_external:
                f.write("# References to base image state files (not inline data)\n")
            f.write("baseImages:")
            if state["baseImages"]:
                f.write("\n")
                for base in state["baseImages"]:
                    f.write(f"  - {base}\n")
            else:
                f.write(" []\n")
            f.write("\n")

            f.write("# Current published state (from registry/Kargo)\n")
            f.write(f"currentVersion: {yv(state.get('currentVersion'))}\n")
            f.write(f"currentDigest: {yv(state.get('currentDigest'))}\n")
            last_built = state.get("lastBuilt")
            if last_built:
                f.write(f"lastBuilt: {yaml.dump(last_built, default_flow_style=True).strip()}\n\n")
            else:
                f.write(f"lastBuilt: null\n")

    def _write_base_image_state(self, state: Dict, file_path: Path):
        yv = self._yaml_value

        with open(file_path, "w") as f:
            f.write(f"# Auto-generated by Image Factory\n")
            f.write(f"# This file tracks the upstream {state['fullImage']} base image\n\n")

            f.write("# Normalized identifier (used as filename and reference)\n")
            f.write(f"name: {state['name']}\n\n")

            f.write("# Original image reference\n")
            f.write(f"fullImage: {state['fullImage']}\n")
            f.write(f"registry: {state['registry']}\n")
            f.write(f"repository: {state['repository']}\n")
            f.write(f"tag: {state['tag']}\n\n")

            f.write("# Warehouse configuration (for CDK8s)\n")
            f.write(f"allowTags: {state['allowTags']}\n")
            f.write(f"imageSelectionStrategy: {state['imageSelectionStrategy']}\n")
            f.write(f"repoURL: {state['repoURL']}\n\n")

            f.write("# Discovery\n")
            f.write(f"firstDiscovered: {yaml.dump(state['firstDiscovered'], default_flow_style=True).strip()}\n")
            f.write(f"lastChecked: {yaml.dump(state['lastChecked'], default_flow_style=True).strip()}\n\n")

            f.write("# Current state\n")
            f.write(f"currentDigest: {yv(state['currentDigest'])}\n")
            f.write(f"lastUpdated: {yv(state['lastUpdated'])}  # Will be set when digest first changes\n")
            f.write(f"previousDigest: {yv(state['previousDigest'])}\n\n")

            f.write("# Rebuild eligibility\n")
            f.write("rebuildEligibleAt:\n")
            f.write(f"  default: {yv(state['rebuildEligibleAt']['default'])}  # Will be calculated as lastUpdated + rebuildDelay\n\n")

            f.write("# Metadata from registry\n")
            if state.get("metadata") and state["metadata"]:
                f.write("metadata:\n")
                for key, value in state["metadata"].items():
                    f.write(f"  {key}: {yaml.dump(value, default_flow_style=True).strip()}\n")
            else:
                f.write("metadata: {}\n")
            f.write("\n")

            f.write("# Update history (last 10 digest changes)\n")
            if state.get("updateHistory"):
                f.write("updateHistory:\n")
                for entry in state["updateHistory"]:
                    f.write(f"  - {yaml.dump(entry, default_flow_style=True).strip()}\n")
            else:
                f.write("updateHistory: []\n")

            if state.get("lastDiscovery") is not None:
                f.write(f"\nlastDiscovery: {yv(state['lastDiscovery'])}\n")
