#!/usr/bin/env python3
"""
cg tools check — CI/CD tool version drift detection.

Reads tools.yaml, generates/updates .cascadeguard/tools/ state files,
queries upstream registries, and reports version drift.

Exit codes:
  0 — all tools up to date
  1 — error (config invalid, registry unreachable)
  2 — updates available
"""

import json
import os
import re
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import yaml


# ---------------------------------------------------------------------------
# Schema / parsing
# ---------------------------------------------------------------------------

VALID_TOOL_TYPES = {
    "github-action",
    "github-reusable-workflow",
    "gitlab-ci-component",
    "gitlab-ci-image",
    "cli-tool",
    "helm-plugin",
}


def parse_tools_yaml(tools_yaml_path: Path) -> list:
    """Load and parse tools.yaml. Returns list of tool dicts."""
    if not tools_yaml_path.exists():
        raise FileNotFoundError(f"tools.yaml not found: {tools_yaml_path}")
    with open(tools_yaml_path) as f:
        data = yaml.safe_load(f)
    if data is None:
        return []
    if not isinstance(data, list):
        raise ValueError("tools.yaml root must be a list")
    return data


def validate_tool_entry(tool: dict) -> list[str]:
    """Return list of validation errors for a tool entry."""
    errors = []
    if not tool.get("name"):
        errors.append("missing required field: name")
    if not tool.get("type"):
        errors.append("missing required field: type")
    elif tool["type"] not in VALID_TOOL_TYPES:
        errors.append(f"unknown type '{tool['type']}'; valid: {sorted(VALID_TOOL_TYPES)}")
    return errors


def normalize_tool_name(name: str) -> str:
    """Convert a tool name to a safe filename stem (e.g. 'actions/checkout' -> 'actions-checkout')."""
    return re.sub(r"[^a-zA-Z0-9._-]", "-", name).strip("-")


# ---------------------------------------------------------------------------
# State file generation
# ---------------------------------------------------------------------------

def load_tool_state(state_file: Path) -> Optional[dict]:
    if not state_file.exists():
        return None
    with open(state_file) as f:
        return yaml.safe_load(f) or {}


def write_tool_state(state_file: Path, state: dict) -> None:
    """Write a tool state file."""
    state_file.parent.mkdir(parents=True, exist_ok=True)
    with open(state_file, "w") as f:
        f.write("# Auto-generated by CascadeGuard\n")
        yaml.dump(state, f, default_flow_style=False, sort_keys=False, allow_unicode=True)


def _initial_state(tool: dict, now: str) -> dict:
    """Build a fresh state dict from a tools.yaml entry."""
    return {
        "name": normalize_tool_name(tool["name"]),
        "type": tool.get("type"),
        "enrolledAt": now,
        "lastChecked": None,
        "registry": tool.get("registry"),
        "repository": tool.get("repository"),
        "currentVersion": tool.get("version"),
        "pinnedRef": tool.get("pinDigest"),
        "latestVersion": None,
        "latestDigest": None,
        "updateAvailable": False,
        "checkStatus": "new",
        "checkError": None,
        "sources": tool.get("sources", []),
        "upstreamVersions": {},
    }


def generate_tool_state(tool: dict, tools_state_dir: Path, now: str) -> tuple[Path, dict]:
    """
    Create or update the state file for *tool*.
    Returns (state_file_path, state_dict).
    """
    fname = normalize_tool_name(tool["name"]) + ".yaml"
    state_file = tools_state_dir / fname

    existing = load_tool_state(state_file)
    if existing:
        # Preserve timestamps and runtime data; refresh catalog fields
        state = dict(existing)
        state["currentVersion"] = tool.get("version", existing.get("currentVersion"))
        state["pinnedRef"] = tool.get("pinDigest", existing.get("pinnedRef"))
        state["sources"] = tool.get("sources", existing.get("sources", []))
    else:
        state = _initial_state(tool, now)

    return state_file, state


# ---------------------------------------------------------------------------
# Registry queries
# ---------------------------------------------------------------------------

def _github_token(config: dict) -> str:
    """Resolve GitHub token from config or environment."""
    token_env = (
        config.get("tools", {})
        .get("check", {})
        .get("registries", {})
        .get("github", {})
        .get("token_env", "GITHUB_TOKEN")
    )
    return os.environ.get(token_env, os.environ.get("GITHUB_TOKEN", ""))


def _github_api_get(path: str, token: str) -> dict:
    """Make a GET request to the GitHub API. Raises urllib.error.HTTPError on failure."""
    url = f"https://api.github.com{path}"
    req = urllib.request.Request(url)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("X-GitHub-Api-Version", "2022-11-28")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.loads(resp.read().decode())


def query_github_action_upstream(owner: str, repo: str, token: str) -> dict:
    """
    Query GitHub for the latest release of a GitHub Action.

    Returns:
      {
        "latestVersion": "v4.2.2",
        "latestDigest": "<commit-sha>",
        "versions": {"v4.2.2": {"digest": "<sha>", "firstSeen": ..., "lastSeen": ...}, ...}
      }
    or raises on error.
    """
    now_iso = datetime.now(timezone.utc).isoformat()
    versions = {}

    # Try releases first, fall back to tags
    try:
        releases = _github_api_get(f"/repos/{owner}/{repo}/releases?per_page=10", token)
        if releases:
            latest_release = releases[0]
            tag_name = latest_release.get("tag_name", "")
            # Resolve tag to commit SHA
            sha = _resolve_github_tag_sha(owner, repo, tag_name, token)
            for rel in releases:
                t = rel.get("tag_name", "")
                s = _resolve_github_tag_sha(owner, repo, t, token)
                versions[t] = {
                    "digest": s,
                    "firstSeen": now_iso,
                    "lastSeen": now_iso,
                }
            return {
                "latestVersion": tag_name,
                "latestDigest": sha,
                "versions": versions,
            }
    except urllib.error.HTTPError as exc:
        if exc.code != 404:
            raise

    # Fall back to tags
    tags = _github_api_get(f"/repos/{owner}/{repo}/tags?per_page=10", token)
    if not tags:
        return {"latestVersion": None, "latestDigest": None, "versions": {}}

    latest = tags[0]
    tag_name = latest.get("name", "")
    sha = latest.get("commit", {}).get("sha", "")
    for t in tags:
        versions[t["name"]] = {
            "digest": t.get("commit", {}).get("sha", ""),
            "firstSeen": now_iso,
            "lastSeen": now_iso,
        }
    return {
        "latestVersion": tag_name,
        "latestDigest": sha,
        "versions": versions,
    }


def _resolve_github_tag_sha(owner: str, repo: str, tag: str, token: str) -> str:
    """Resolve a tag name to its commit SHA via the GitHub API."""
    try:
        ref = _github_api_get(f"/repos/{owner}/{repo}/git/ref/tags/{tag}", token)
        obj = ref.get("object", {})
        if obj.get("type") == "commit":
            return obj.get("sha", "")
        # Annotated tag — dereference
        if obj.get("type") == "tag":
            tag_obj = _github_api_get(
                f"/repos/{owner}/{repo}/git/tags/{obj['sha']}", token
            )
            return tag_obj.get("object", {}).get("sha", "")
        return obj.get("sha", "")
    except Exception:
        return ""


def query_upstream(tool_type: str, owner: str, repo: str, config: dict) -> dict:
    """
    Dispatch to the appropriate registry query for *tool_type*.
    Returns the same shape as query_github_action_upstream.
    """
    token = _github_token(config)
    if tool_type in ("github-action", "github-reusable-workflow"):
        return query_github_action_upstream(owner, repo, token)
    # Other types not yet implemented — return empty result
    return {"latestVersion": None, "latestDigest": None, "versions": {}}


def _parse_owner_repo(tool: dict) -> tuple[str, str]:
    """Extract (owner, repo) from tool dict."""
    repository = tool.get("repository", tool.get("name", ""))
    # Handle monorepo sub-paths: owner/repo/subpath -> owner, repo
    parts = repository.split("/")
    if len(parts) >= 2:
        return parts[0], parts[1]
    return repository, ""


# ---------------------------------------------------------------------------
# Drift detection
# ---------------------------------------------------------------------------

def detect_drift(tool: dict, state: dict, upstream: dict) -> dict:
    """
    Compare current version against upstream and return updated state.

    Returns updated state dict with checkStatus, latestVersion, updateAvailable.
    """
    latest = upstream.get("latestVersion")
    current = state.get("currentVersion") or tool.get("version")

    state["latestVersion"] = latest
    state["latestDigest"] = upstream.get("latestDigest")
    state["lastChecked"] = datetime.now(timezone.utc).isoformat()
    state["checkError"] = None

    # Merge upstream versions (preserve firstSeen)
    existing_versions = state.get("upstreamVersions") or {}
    for ver, info in (upstream.get("versions") or {}).items():
        if ver in existing_versions:
            merged = dict(existing_versions[ver])
            merged["lastSeen"] = info["lastSeen"]
            if "digest" in info:
                merged["digest"] = info["digest"]
            existing_versions[ver] = merged
        else:
            existing_versions[ver] = info
    state["upstreamVersions"] = existing_versions

    if latest is None:
        state["checkStatus"] = "ok"
        state["updateAvailable"] = False
        return state

    if current is None:
        state["checkStatus"] = "new"
        state["updateAvailable"] = False
        return state

    # Normalise for comparison (strip leading 'v')
    def _strip_v(s: str) -> str:
        return s.lstrip("v") if isinstance(s, str) else s

    if _strip_v(latest) != _strip_v(current):
        state["checkStatus"] = "update-available"
        state["updateAvailable"] = True
    else:
        state["checkStatus"] = "ok"
        state["updateAvailable"] = False

    return state


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

def _row(name: str, current: Optional[str], latest: Optional[str], status: str, error: Optional[str]) -> str:
    cur = current or "-"
    lat = latest or "-"
    if status == "ok":
        flag = "ok"
    elif status == "update-available":
        flag = "UPDATE"
    elif status == "new":
        flag = "new"
    elif status == "error":
        flag = f"ERROR: {error or 'unknown'}"
    else:
        flag = status
    return f"  {name:<40} {cur:<20} {lat:<20} {flag}"


def output_results(results: list, fmt: str) -> None:
    if fmt == "json":
        print(json.dumps(results, indent=2))
        return

    # Table
    if not results:
        print("No tools checked.")
        return
    header = f"  {'Tool':<40} {'Current':<20} {'Latest':<20} Status"
    print(header)
    print("  " + "-" * 85)
    for r in results:
        print(_row(r["name"], r.get("currentVersion"), r.get("latestVersion"), r["status"], r.get("error")))


# ---------------------------------------------------------------------------
# State commit (mirrors images check pattern)
# ---------------------------------------------------------------------------

def _commit_tool_states(state_files: list[Path], repo_root: Path, no_commit: bool) -> None:
    """Commit updated tool state files to git."""
    if no_commit:
        return
    import subprocess
    try:
        for sf in state_files:
            subprocess.run(
                ["git", "add", str(sf)],
                cwd=repo_root,
                check=True,
                capture_output=True,
            )
        result = subprocess.run(
            ["git", "diff", "--cached", "--quiet"],
            cwd=repo_root,
            capture_output=True,
        )
        if result.returncode == 0:
            return  # Nothing to commit
        subprocess.run(
            ["git", "commit", "-m", "chore: update tool state files [skip ci]"],
            cwd=repo_root,
            check=True,
            capture_output=True,
        )
    except subprocess.CalledProcessError as exc:
        print(f"Warning: git commit failed: {exc}", file=sys.stderr)


# ---------------------------------------------------------------------------
# Main command
# ---------------------------------------------------------------------------

def cmd_tools_check(args) -> int:
    """
    Entry point for `cg tools check`.

    Returns:
      0 — all tools up to date
      1 — error
      2 — updates available
    """
    tools_yaml_path = Path(args.tools_yaml)
    if not tools_yaml_path.exists():
        print(f"Error: tools.yaml not found: {tools_yaml_path}", file=sys.stderr)
        return 1

    repo_root = tools_yaml_path.parent
    state_dir = Path(args.state_dir)
    tools_state_dir = state_dir / "tools"
    tools_state_dir.mkdir(parents=True, exist_ok=True)

    tool_filter: Optional[str] = getattr(args, "tool", None)
    fmt: str = getattr(args, "format", "table")
    no_commit: bool = getattr(args, "no_commit", False)

    # Load config for token resolution
    from app import load_config
    config = load_config(repo_root)

    # Parse tools
    try:
        tools = parse_tools_yaml(tools_yaml_path)
    except (FileNotFoundError, ValueError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    now = datetime.now(timezone.utc).isoformat()
    results = []
    state_files_written = []
    has_error = False
    has_updates = False

    for tool in tools:
        name = tool.get("name", "")
        if tool_filter and name != tool_filter:
            continue

        errors = validate_tool_entry(tool)
        if errors:
            print(f"  {name}: invalid entry — {'; '.join(errors)}", file=sys.stderr)
            results.append({"name": name, "status": "error", "error": "; ".join(errors)})
            has_error = True
            continue

        tool_type = tool.get("type")
        state_file, state = generate_tool_state(tool, tools_state_dir, now)

        # Query upstream (only for supported types with known owner/repo)
        owner, repo = _parse_owner_repo(tool)
        upstream_ok = True
        if tool_type in ("github-action", "github-reusable-workflow") and owner and repo:
            try:
                upstream = query_upstream(tool_type, owner, repo, config)
                state = detect_drift(tool, state, upstream)
            except urllib.error.HTTPError as exc:
                state["checkStatus"] = "error"
                state["checkError"] = f"HTTP {exc.code}: {exc.reason}"
                state["lastChecked"] = now
                upstream_ok = False
                has_error = True
            except Exception as exc:
                state["checkStatus"] = "error"
                state["checkError"] = str(exc)
                state["lastChecked"] = now
                upstream_ok = False
                has_error = True
        else:
            # Unsupported type for upstream query — just record state
            if state["checkStatus"] == "new":
                state["checkStatus"] = "ok"
            state["lastChecked"] = now

        write_tool_state(state_file, state)
        state_files_written.append(state_file)

        status = state.get("checkStatus", "ok")
        result_entry = {
            "name": name,
            "status": status,
            "currentVersion": state.get("currentVersion"),
            "latestVersion": state.get("latestVersion"),
        }
        if not upstream_ok:
            result_entry["error"] = state.get("checkError")
        results.append(result_entry)

        if status == "update-available":
            has_updates = True

    output_results(results, fmt)

    # Commit state files
    _commit_tool_states(state_files_written, repo_root, no_commit)

    if has_error:
        return 1
    if has_updates:
        return 2
    return 0
